### ISSUE TITLE
Relationship with brix/CryptoJS

### ISSUE THREAD

**Issue by samvv** [sytelus/CryptoJS#6]
I have created an issue in [brix/crypto-js](https://github.com/brix/crypto-js/) about the relationship between these two libraries, and if it would be possible to merge. You can view it here: https://github.com/brix/crypto-js/issues/53. I would propose, for convenience, holding discussions over there.

**Comment by sytelus** [comment]
@samvv thanks for bringing this up. The sytelus/CryptoJS is meant to hold exact replica of original version in SVN. At the time, purpose was not to create a fork for development and this is why its not been changing. If SVN version ever gets updated then I would update this replica as well. However, I'm not too sure about merging other updates and fixes, primarily because any changes to this library needs to be rigorously tested. So unless I can trust those updates, I would be very reluctant to merge them with original SVN replica. I know this is not the best approach. May be the alternative is to create a branch here with all the updates other folks are doing so people can chose to get latest and greatest OR original.

**Comment by samvv** [comment]
Ok I understand: brix = updates/features/unsafe, yours = original/no updates/safe. I guess then that it indeed isn't possible or necessary to merge then. Thanks for explaining!

By the way: in my opinion there's no need for creating extra branches if brix supports this.
